### ISSUE TITLE
422 Unprocessable Entity

### ISSUE THREAD

**Issue by delapohl** [rentpath/portal_integration_samples#8]
I'm running into an issue where the Portal host is returning an error (422 Unprocessable Entity), apparently when Media Center attempts to retrieve a new access token while a MyAG session persists. Test case:

1. Log in to MyAG
2. Go to Media Center
3. OAuth dance completes without issue
4. Media Center app receives an access token from the Portal host
5. Media Center stores the access token in session
6. [wait several hours]
7. Media Center session expires, but MyAG session persists
8. Media Center re-initiates the OAuth dance and requests/receives a new request token (code)
9. Media Center attempts to exchange the request token for an access token
10. Portal host returns 422 Unprocessable Entity

If the user explicitly logs out of and then logs back into MyAG, then the Media Center app receives an OAuth access token without issue.

**Comment by Ebtoulson** [comment]
This was resolved early February, closing issue.
